### ISSUE TITLE
Selecting members of sub arrays results in merged objects.

### ISSUE THREAD

**Issue by gak10100** [kofrasa/mingo#105]
Code
```
var result = mingo.find(
  [
    { 
      items: [
        { from: 1 },
        { to: 2 }
      ]
    }
  ], 
  {}, 
  { 'items.from': 1, 'items.to': 1 }
).all();
```

Result
```
[
  { 
    items: [
      { from: 1, to: 2 }
    ]
  }
]
```

Expected Result
```
[
  { 
    items: [
      { from: 1 },
      { to: 2 }
    ]
  }
]
```

**Comment by kofrasa** [comment]
Thanks for creating this issue @gak10100.

This is familiar and related to some older issues (https://github.com/kofrasa/mingo/issues/91 and https://github.com/kofrasa/mingo/issues/93) which I already closed.

The problem lies with not being able to distinguish `[ { from: 1, to: 2 } ]` from `[ { from: 1 } , { to: 2 } ]` when projecting by nested keys. 

To get around this we can try to validate the parent size of the matched sub-document with the root since the processing is done per key. If the sizes differ, we avoid flattening during the merge otherwise we flatten.
