### ISSUE TITLE
Import breaks when using babel to convert es module syntax targeting node

### ISSUE THREAD

**Issue by SamTolmay** [kofrasa/mingo#130]
On version 2.5.2, when mingo is imported using es6 syntax, and babel is used to transform the code, mingo is not imported by the transformed code. This also happens when using a babel loader with jest.

For a reproduction, see: https://github.com/SamTolmay/mingo-import-reproduce.git

**Comment by kofrasa** [comment]
Thanks for the report @SamTolmay  and also taking the time to create a repo. I will run your examples to see what exactly is breaking.

**Comment by SamTolmay** [comment]
Thank you

**Comment by kofrasa** [comment]
The issue seems to be the missing [default](https://github.com/kofrasa/mingo/blob/6f9dc31cce5723abaf3245b04fccd0c6d7e139d5/index.js) export in the latest version. Consequently the new import syntax would be as below, which is not ideal. I will fix and publish a new version shortly. Thanks again for the effort in setting up a repro.

```js
import * as mingo from 'mingo'
```
