### ISSUE TITLE
Not always safe to rely on the constructor property of an object

### ISSUE THREAD

**Issue by carsonfarmer** [kofrasa/mingo#141]
I'm having some issues with mingo in certain JS environments. For instance, object literals _don't_ always have constructor === Object, which is a check performed here: https://github.com/kofrasa/mingo/blob/master/src/util.ts#L92. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor#Changing_the_constructor_of_an_object for why this isn't always a good idea.

Here's an alternative that works: https://stackoverflow.com/questions/8511281/check-if-a-value-is-an-object-in-javascript/8511350#8511350

**Comment by kofrasa** [comment]
Thanks for the report @carsonfarmer. 

So this is an interesting one as the function is meant to test for an instance of the base JS [Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) type and not derivatives such as  `Array` or `Boolean`. Should a user explicitly change the constructor function the object will cease to be valid since after going through the `mingo` pipeline, the custom constructor information may not be retained.

This explicitly require users to always provide a source the produces vanilla JS object literals and avoids the complexity of having to deal with custom types. In effect I am relying on the unsafe behaviour precisely to achieve this so that there is no ambiguity. 

All the other options for object type checking will mask custom types. These include;

```js
function Type() {}
typeof (new Type())                           // 'object'
Object.prototype.toString.call(new Type())    // '[object Object]'

typeof (new Array())                          // 'object'
Object.prototype.toString.call([])            // '[object Array]'
[] instanceof Object                          // true
```

I provide an alternative function [isObjectLike](https://github.com/kofrasa/mingo/blob/master/src/util.ts#L93) that works will all objects.

Perhaps they are poorly named. Accurately they should be changed to reflect their actual semantics as in;

- `isObject` -> `isObjectLiteral` 
- `isObjectLike` -> `isObject`

Some people may already depend on these functions directly so I will leave them as is for now and consider renaming them in a future version.

**Comment by carsonfarmer** [comment]
I fact, I am dealing with object literals... but they are being run through a compiler (bundler) which is 'converting' them to something that doesn't satisfy the constraints in isObject, hence the issue. For the time being, I am also actually taking advantage of the unsafe behavior of isObject to trick it into thinking my objects _are_ indeed object literals... this should work for now 🤷.
