### ISSUE TITLE
fully built/distributable version

### ISSUE THREAD

**Issue by Nashorn** [kofrasa/mingo#152]
Could someone provide a link to a fully built/distributable version in a single .js please

**Comment by kofrasa** [comment]
This project no longer provides a single distributed file. It should be trivial to create one by checking out the source and executing the typescript compiler with your own [configuration](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

I would not recommend a single distributable file though since the library has grown large and now provides the ability to only include operators that you actually use in your application. This works well with the popular bundling tools like `babel` or `webpack` which will tree-shake to remove unused functions.

**Comment by kofrasa** [comment]
Resolving this issue as there is nothing more to do.
