### ISSUE TITLE
Passing pipeline in $lookup

### ISSUE THREAD

**Issue by gotdan** [kofrasa/mingo#154]
Does mingo support passing a pipeline object to a $lookup stage - I'm getting an invalid argument error (https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/#join-conditions-and-uncorrelated-sub-queries)? If not, is this on the roadmap? Thanks!

**Comment by kofrasa** [comment]
That is not yet supported. Please feel free to submit a PR

**Comment by RezaErfani67** [comment]
how can i use $lookup
```javascript
let agg = new Aggregator([
    {'$match': { "type": "homework"}},
    {'$lookup': {
        from: 'students', // The STRING!
        localField: "who",
        foreignField: "nickName",
        as: "profile"
    }},
])

```

**Comment by kofrasa** [comment]
Currently the input needs to be the action collection reference (i.e `Array`) to lookup from. This is because `mingo` does not manage collections and only provides the query engine. There is an issue https://github.com/kofrasa/mingo/issues/150 to support collection resolvers so that you can register functions to return collections that map to the given string name. This will be made available in the next release.

**Comment by kofrasa** [comment]
Resolving in favour of https://github.com/kofrasa/mingo/issues/150
