### ISSUE TITLE
Comparison operators return a function value

### ISSUE THREAD

**Issue by Gervwyk** [kofrasa/mingo#160]
First of all, thanks for this excellent library!

Running in 3.1.0.
The following returns a function instead of a boolean as the result of a $eq operator.
```
const agg = new mingo.Aggregator([{"$project":{"value":{"$eq":[5,5]}}}]);
const res = agg.run([{ a: 1 }]);  
// returns [ { value: [Function (anonymous)] } ]
// expected [ { value: true } ]
```
Calling `res[0].value()` returns `true`.
Same behaviour for other comparison operators.

Is this a bug?

**Comment by kofrasa** [comment]
Hi @Gervwyk, thanks for submitting this issue. `Aggregator#run` should return the realized value as expected.

I have tested this here https://runkit.com/embed/r87j4ic3ked7 using exactly the code you posted.

Can you recheck your test and confirm if you are doing something different.

**Comment by Gervwyk** [comment]
Thanks. We have it set up [here](https://github.com/lowdefy/lowdefy/blob/main/packages/operators/src/operators.js).

I've managed to reproduce it in runkit: https://runkit.com/gervwyk/5fde6fce91460d0013a104d9

Is this setup correct?

**Comment by kofrasa** [comment]
I was able to reproduce and fix the issue here. https://runkit.com/embed/74wp7z21f7mx

There was a mistake in registering the operators. You swapped `query` and `projection` operators. The interfaces are different for different operator types. See [docs](https://github.com/kofrasa/mingo/wiki/Custom-Operators).

If you want to import all operators you just use the short-cut. 

```typescript
import 'mingo/init/system'
```

No need to import them one at a time. That is provided mostly for those who care about bundle size, say if deploying to a browser environment.

**Comment by Gervwyk** [comment]
O shoot. Don't know how me missed that, will change to system import. Sorry about the typo and thanks for the help!
