### ISSUE TITLE
Support for geospatial queries

### ISSUE THREAD

**Issue by vdininski** [kofrasa/mingo#18]
Is support for geospatial queries planned and what are the expected limitations?

**Comment by kofrasa** [comment]
Yes it is, but not a priority since no demand for it has been made. Like the rest of the operators, it will follow the same behaviour as the MongoDB implementations. You are welcome to submit a pull request. Alternatively if you need only a subset of the features, you could write them as a custom operators, a feature available in the latest release :)

**Comment by kofrasa** [comment]
There are no plans to implement this as part of this library. Another library extending `mingo` with the necessary custom operators will be most appropriate.
