### ISSUE TITLE
Add $dateAdd/$dateSubtract operators

### ISSUE THREAD

**Issue by MattIPv4** [kofrasa/mingo#194]
Hey!

I noticed that the `$dateAdd` and `$dateSubtract` operators aren't currently implemented. It'd be great if these were added as they're supported in native Mongo for date manipulations.

---

I ended up doing the following to patch in `$dateAdd` locally for a project I'm working on:

```
const { addOperators, OperatorType } = require('mingo/core');
const dayjs = require('dayjs');

addOperators(OperatorType.EXPRESSION, helpers => {
    return {
        /**
         * Mingo dateAdd operator -- increments a Date object by a specified number of time units
         * @param {Object.<*, *>} collection - Input data to the mingo query
         * @param {{startDate: Date, unit: string, amount: number}} expr - Input expression to this expression
         * @param {Object.<*, *>} options - Mingo query options
         * @returns {Date}
         */
        $dateAdd: (collection, expr, options) => {
            const date = helpers.computeValue(collection, expr.startDate, null, options);
            const unit = helpers.computeValue(collection, expr.unit, null, options);
            const amount = helpers.computeValue(collection, expr.amount, null, options);
            return dayjs(date).add(amount, unit).toDate();
        },
    };
});
```

I imagine this'd work in the source here as well, but I noticed all the existing date stuff is done by hand without any libraries?

**Comment by kofrasa** [comment]
Hi @MattIPv4 ,

Thanks for opening this issue. There are a lot of operators that have not been implemented mostly due to time constraints. 

I am open to PRs for missing operators and also will try to implement some of them from time to time.

The MongoDB operators library is huge and grows with each new version so it is hard to keep up. The custom operator interface is provided to fill in where this library is slow to catch up, so I am glad you found that useful.

**Comment by MattIPv4** [comment]
Would you be happy with a dependency being introduced to support some of these operators (e.g. `dayjs` for the date manipulation ones)?
