### ISSUE TITLE
Proxy clone instead of direct utils/cloneDeep 

### ISSUE THREAD

**Issue by kpmy** [kofrasa/mingo#202]
Hi!

After intensive usage in production I discovered that cloning objects inside pipelines gets very heavy after two or more unwinds or groupings (70k clones for typical report request in my project).

Therefore I made a proxyCloneDeep function, that replaced your default clone function.

For now it looks pretty dumb, but pipeline speedup is insane :).

So, can you add as an option solution like this? I think it can be even implemented as default behavior.

```
const fk = require('./util/fake.copy')
const { aggregate, Aggregator } = require('mingo')
const {addOperators, OperatorType} = require('mingo/core')
const mingoUtil = require('mingo/util')
//boooost
mingoUtil.cloneDeep = (obj) => fk.fakeCopy(obj)
require('mingo/init/system')
```

fake,copy is my own bycicle with inner data analysis (corporate stuff, you know), but here is similar library https://www.npmjs.com/package/proxy-clone

In my case I don't need de-proxing, but that will be usefull too

**Comment by kofrasa** [comment]
Thanks for raising this issue @kpmy and I am glad you are finding this library useful. 

To the topic, while performance has not been a big focus of this library I like to make improvements here and there. Cloning objects for the pipeline was not the best solution at the time but the simplest and safest approach. I had not yet added per query options. I would prefer not to clone objects at all for use cases that can survive the input documents getting modified in order to gain a speed up. Not all use cases need to retain the original documents as is, and cloning is only relevant for specific cases. To avoid unintended surprises though led to the current approach.

I appreciate the suggestion above and have considered it. I don't think allowing `cloneDeep` to be configured is the best path forward because it is a fundamental operation in the library and there will be valid uses for it. The package you referenced was helpful. I didn't know about the [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object before. I believe a similar approach to cloning can work given two conditions;

1. The clone passes the `isObject` test which expects the prototype to be equivalent to that of a plain object literal.
2. The clone operation works correctly for nested container values like arrays.

The first condition seems to be covered [here](https://github.com/juliangruber/proxy-clone/blob/master/index.js#L46) but unfortunately, the second is not covered so modifying an array of a cloned object modifies the array in the original. This is a common drawback for most proxy implementations that want to offer dynamic properties on objects. They also require users to assign to array fields directly rather use mutations because those cannot be faked without replacing the actual array object.

We can give it some more time to develop new ideas but also feel free to take a stab at adding an option to skip deep cloning objects in the pipeline when it is not required.

It is currently used in four operators; `$unwind`, `$redact`, `$project`, and `$addFields`.

**Comment by kpmy** [comment]
OK, I see. Of course, general approach will remain as it was, deepClone. But in case of this proxy-clone approach base object can remain immutable because of mutability layers that proxy creates instead of modifying base object. Even arrays CAN be wrapped to proxy. Main reason why I'm using it was pipeline like {$group: {_id... _items: {$push: "$$CURRENT"}} for reports with expanding rows. If you do such grouping twice, you'll get a massive immutable cloning.

Trick that I proposed works for now, and I understand your way to support input data immutability, but don't you think, that pipeline engine should work on different approach. With such a proxy-mutable-space you can get efficiency on memory and cpu usage.

Maybe such approach should be implemented as an optional objectFactoryFn, like resolveFn in current version.

**Comment by kofrasa** [comment]
I am happy to break immutability by way of an opt-in function. The solution with proxies may not be appropriate because the user still has to make assumptions about the results. If we have to deep clone at the end then we are already losing the benefit. Using an opt-in, the expectation is well defined. If you don't care about the input documents' immutability then you can run your query with an option, say `disableCloning` and then get the speed up.

**Comment by kofrasa** [comment]
@kpmy 

On master branch, I have pushed a new change that uses object sharing for pipeline operations unless explicitly disabled. The option is called `processingMode` and is initialized with the value `ProcessingMode.CLONE_OFF` as the default. You should get some speed increase for your use case if your objects are very large.

Will appreciate if you can test and let me know whether you see improvement. Thanks

**Comment by kofrasa** [comment]
Resolved in https://github.com/kofrasa/mingo/commit/9dffc01c9d9e40e4e13c74838601a8ef3aa2b24f with the new `ProcessingMode.CLONE_OFF` option.
