### ISSUE TITLE
Await async iterators

### ISSUE THREAD

**Issue by SteffenLanger** [kofrasa/mingo#213]
**Use Case**
We query data from a local IndexedDB via [idb](https://github.com/jakearchibald/idb) using a cursor. The IndexedDB contains about 20,000+ CRM records that might make a mobile device really slow when read into RAM all at once. That's why we would love to use mingo's Lazy loading ability.

**Issue**
The idb cursor works asynchronously, so we need to await the `next()` call of the iterator according to this [Stackoverflow question](https://stackoverflow.com/questions/36107171/how-do-i-use-await-inside-a-generator). However, mingo does not await the `src.next()` call ([Source](https://github.com/kofrasa/mingo/blob/ef2c4c63d4a1bb4d8466e63d970e56cbc91ce47d/src/lazy.ts#L164)):
```typescript
    if (isGenerator(source)) {
      const src = source as Generator<AnyVal>;
      nextVal = () => {
        const o = src.next() as RawObject;
        if (o.done) throw DONE;
        return o.value;
      };
    } else if (source instanceof Array) {
      const data = source;
      const size = data.length;
      let index = 0;
      nextVal = () => {
        if (index < size) return data[index++];
        throw DONE;
      };
    } else if (!(source instanceof Function)) {
      throw new Error(
        `Source is of type '${typeof source}'. Must be Array, Function, or Generator`
      );
    }
```

**Solution**
I'd propose to await the `src.next()` call. What do maintainers think about that?

**Comment by kofrasa** [comment]
Supporting `async` operations within the library has several complications and it not ideal for most use cases. An async data source is also incompatible with the `Aggregation` framework which operates over a fully realized set of documents. 

If you want to access the filtering and projection capabilities, then you can decouple your data retrieval from processing and use the `Query` object directly.

Below is a very simplified example. Note that collecting the objects from your datasource can be batched for performance.

```js
// assuming we are in an async context
const query = new Query(criteria)
const idb = getCursor()
const results = []

try {
  while (true) {
   // we expect idb.next() to throw when exhausted
    const obj = await idb.next()
   // NOTE: you can implement batching to minimize the number of calls to query.find
    result.push(...query.find([ob], projection).all())
  } catch (err) {}

  return Promise.resolve(results)
}

```

If all you are using Mingo for is filtering out the documents, you can use `query.test(obj) -> boolean` instead of `query.find(obj)`.

**Comment by SteffenLanger** [comment]
How would you propose using `.limit()` and `.sort()` in this case? I'd assume that these two methods would have to be implemented with another query call that's applied to the `results` array in your example above, like so:

```javascript
// assuming we are in an async context
const query = new Query(criteria)
const idb = getCursor()
const results = []

try {
  while (true) {
   // we expect idb.next() to throw when exhausted
    const obj = await idb.next()
   // NOTE: you can implement batching to minimize the number of calls to query.find
    result.push(...query.find([ob], projection).all())
  } catch (err) {}

  return Promise.resolve(query.find(results).sort(sortCriteria).limit(limitNumber));
}
```

**Comment by kofrasa** [comment]
You will have to make some tradeoffs. Like other aggregation pipeline operators, sorting requires the fully realized result set.  In my suggestion above, you will have no need for the `Cursor` returned from executing your query hence the `.all()`. If you want to limit the returned results, that would have to be done either before or after filtering depending on your use case. Either way it would be better to implement that manually. For sorting you use another `Query` after collecting all your data.

**Comment by kofrasa** [comment]
Unfortunately `async` functions do not compose  well with `sync` functions in JS. Since this library targets in-memory data manipulation it is best to keep it decoupled from any data retrieval process especially one using async callbacks or promises. The `Aggregator` will be useless in that case since it needs as input an array of data. The `Query` class is still very useful so long as you are only processing your objects one at a time. You still get access to all the existing expression operators via the `$expr` operator.  The generator interface is only provided to support streaming  which is not necessarily the same as async.

**Comment by SteffenLanger** [comment]
Yep, sounds reasonable! Thank you for taking the time to discuss this 💪🏼
