### ISSUE TITLE
Please support query with mongoose ObjectId

### ISSUE THREAD

**Issue by kitce** [kofrasa/mingo#22]
Please consider the following situation:
```
// users
[
  {
    _id : ObjectId("1"),
    someKey : "someValue"
  }
]
```
```
	var query = new Mingo.Query({_id : 1});
	var cursor = query.find(users);
	return cursor.all(); // [] empty array, but it should contain {_id : ObjectId("1"), someKey : "someValue"}
```
Looking forward to this!

**Comment by kofrasa** [comment]
What you have as your example is expected since the types are different. Perhaps you should search using the query ```{_id: ObjectId("1")}```. I would expect that to give some kind of error since the library is currently is unaware of user-defined types. This was not priority given the goals of this project but it is feasible and I think without much effort.

**Comment by kofrasa** [comment]
Added support for matching against user-defined types in release [0.6.4](https://github.com/kofrasa/mingo/releases/tag/0.6.4)
