### ISSUE TITLE
Feature planning: Mongo update operators

### ISSUE THREAD

**Issue by cboar** [kofrasa/mingo#253]
Hi, thanks for building this feature-rich library!

I'm looking to extend the library by adding a new `Updater` class, which aims to implement [the various MongoDB update operators](https://www.mongodb.com/docs/upcoming/reference/operator/update/).

The basic API would look something like this:
```javascript
import { Updater } from "mingo";

const updater = new Updater({
  $set: { status: "complete" },
  $unset: { draft: 1 },
  $inc: { stage: 1 },
  $push: { updates: 1662506580000 },
});

const input = {
  status: "incomplete",
  draft: true,
  stage: 4,
  updates: [1662506420000],
};

const result = updater.applyUpdate(input);
expect(result).toMatchObject({
  status: "complete",
  stage: 5,
  updates: [1662506420000, 1662506580000],
});
```
In order to support both mutable and immutable updates, I would aim to write all the operators in a mutable manner. Then, when an immutable update is desired, the object can first be wrapped as a draft using the [immer JS library](https://immerjs.github.io/immer/). Therefore we will be able to apply immutable updates in an efficient manner, without having to deep-clone or rewrite operators in an immutable fashion.

I'm hoping to get a start on this and submit an initial proof-of-concept PR. Let me know if you have any thoughts, or if you're keen on working on this as well :) Thanks!

**Comment by cboar** [comment]
After some research, it seems that the only operator that even supports any use of Mongo expressions is `$pull`. With that being the case, I will likely opt to have my implementation as a separate project, as the use-cases do not quite overlap.

**Comment by kofrasa** [comment]
Thanks @cboar. I think this will be ideal for a separate project. My observation is that you can achieve most updates using the query operators since they support transforms but another library providing the update API may be more desirable for some users.

**Comment by kofrasa** [comment]
@cboar Since this was last discussed I have needed the update operators for a different project and found it useful to add them to this one given the dependence on queries. This library is modular and tree-shakable for the web, so supporting them here seems appropriate.

There is a single update function `updateObject` which updates the given object in place so there is no need for an immutable representation. Furthermore, the focus is on updating single objects instead of collections. My hunch is that the update operations will be more relevant for single objects for the majority of use cases. 

You can find the changes in `6.4.0` which I will be pushing out soon. Just wanted to give you a heads up should you need this functionality.

Happy coding 👍
