### ISSUE TITLE
Strange behaviour in $round

### ISSUE THREAD

**Issue by Gervwyk** [kofrasa/mingo#304]
Hi, Thanks for the awesome project!

Found strange behaviour for `$round`. Please see the following:
```js
let agg = new Aggregator([
  { $project: { 
        A: {$round: [ '$value', 3]},
        B: '$value'
  } }
]);
let result = agg.run([{ value: 1.6016 }]);
// result is: [{ A: 1.601, B: 1.602 }]
```
I know, that Mongo implements a better statistical rounding algorithm, (https://www.mongodb.com/docs/manual/reference/operator/aggregation/round/#rounding-to-even-values), but in the case of ...16 I'd expect it to round to ...2 not ...1. Is this intentional for some reason?

Thanks again.

**Comment by kofrasa** [comment]
This is the equivalent from MongoDB. https://mongoplayground.net/p/HBcC9QA5sRB
```
[
  {
    "A": 1.602,
    "B": 1.6016,
    "_id": ObjectId("5a934e000102030405000000")
  }
]
```

It should round to `2` as the last digit for A and leave B untouched. There is a bug in `mingo` implementation [here](https://github.com/kofrasa/mingo/blob/83377cabb16f073bf1fafba8b55f095608afee55/src/operators/expression/arithmetic/_internal.ts#L7).  This [line](https://github.com/kofrasa/mingo/blob/83377cabb16f073bf1fafba8b55f095608afee55/src/operators/expression/arithmetic/_internal.ts#L31) should be `>= 5` to fix the value for `A`. As for `B` we need to check what the default places in MongoDB is. Since this library mostly reverse engineer from behaviour, there are a few gaps here and there.

Feel free to submit a PR.

**Comment by kofrasa** [comment]
It seems the `B` value is correct in `mingo`. see https://runkit.com/embed/l8o7ew3s2m2r

**Comment by kofrasa** [comment]
There is more to the fix here. From MongoDB docs

> When rounding on a value of 5, 
[$round](https://www.mongodb.com/docs/manual/reference/operator/aggregation/round/#mongodb-expression-exp.-round)
 rounds to the nearest even value.
