### ISSUE TITLE
Streaming Aggregation

### ISSUE THREAD

**Issue by whitfin** [kofrasa/mingo#38]
It seems that there's no reason why aggregations can't be streamed, is there a chance support can be added for this?

**Comment by kofrasa** [comment]
Thanks for the question zackehh.

I did consider streaming aggregations early in the implementation, but then realized that it is not feasible due to `$group` and `$sort` operations which must operate on the entire collection.

The current streaming implementation for queries is not lazy and it was introduced to mimic MongoDB API interface so users can almost copy + paste code. That said, it is possible to do streaming subject to these constraints.

1.  Ensuring the collection is immutable
2. Enforcing rules for streaming functionality (no $sort, $group etc)

Streaming can be implemented in one of two ways.
1. Using an iterator with chained functions
2. Using the new coroutine and/or generator functions in modern javascript.

Although I haven't settled on a position yet, there are some constraints I have place on the project to guide development. This include making `Mingo` a zero-dependency library and backward compatible for not too old browser version. So these will inform the implementation choice.

Please let me know whether this answers your question.

Thanks.

**Comment by kofrasa** [comment]
Added in  v`2.1.0`. See https://github.com/kofrasa/mingo/wiki/API

**Comment by kofrasa** [comment]
For special cases (`$sort`, `$group` etc) the entire sequence is realized, processed, and a new iterator (stream object) is returned.
