### ISSUE TITLE
More Info Please

### ISSUE THREAD

**Issue by zoomclub** [kofrasa/mingo#4]
This looks like a great project, just need some more intro info, like what the purpose of your API is and how it compares. Does it work on all collection types or any deserialized JSON? Can it be used to query Firebase documents? Can it augment the Firebase query API?

**Comment by kofrasa** [comment]
The goal of the project is to provide MongoDB style queries for direct in-memory javascript collections/objects, mainly for the client side.

**Comment by zoomclub** [comment]
Your project achieves a great goal. I took the mongoDB course a while back and was impressed with its query language. At the same time I was settling on Firebase and found that it did not have the same depth of query abilities, although Firebase queries have become more robust.

https://www.firebase.com/blog/2014-11-04-firebase-realtime-queries.html

It would be super to have mongoDB level querying directly in Firebase, when retrieving remote documents. Firebase maintains a data structure that makes collaboration possible and as I understand it this makes some queries more difficult. Still it will now be possible to make MongoDB style queries on Firebase documents that have been loaded into the client.

It might be worth investigating if your project can be used further directly with Firebase...

**Comment by kofrasa** [comment]
I have not explored Firebase myself but the link suggest they offer limited querying support as compared to mongoDB. However, as long as the documents are available on the client-side, Mingo can be used to fill the query gap as you already pointed at. 

For large documents, a great advantage comes from using NodeJS with the JSON stream library. This allows you to search your document as it is being downloaded. I currently don't have this support for browsers due to lack of a proper JSON streaming library.
