### ISSUE TITLE
webpack critical dependencies warnings

### ISSUE THREAD

**Issue by ksloan** [kofrasa/mingo#40]
Seeing this warning with webpack:

```
webpackHotDevClient.js:196./~/mingo/mingo.js
Critical dependencies:
24:59-66 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/mingo/mingo.js 24:59-66

webpackHotDevClient.js:196./~/mingo/dist/mingo.min.js
Critical dependencies:
1:5762-5769 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/mingo/dist/mingo.min.js 1:5762-5769
```

possibly related to https://github.com/webpack/webpack/issues/2675#issuecomment-269417932 ?

Loving this project by the way! Thanks!

**Comment by kofrasa** [comment]
Can you please provide some more details on what you are trying to do and how?

The issue you referred to about webpack seem to suggest this occurs when attempting to require a variable. 

If I am interpreting the above errors correctly, webpack is complaining about [line 24](https://github.com/kofrasa/mingo/blob/master/mingo.js#L24) which refers to the ```require``` function object. This should not be a problem unless your environment does not define a require function (e.g. browser).

If that is the case consider declaring the variable ```var require;``` before importing the library to see if that works.

Of course take all this with a bit of salt since I do not use webpack myself and by no means an expert.

**Comment by ericfong** [comment]
same problem here. 

using webpack 2.2.1 and babel 6.22.1

I think webpack us regex to detect 'require' and throw because it cannot determine the requiring file path for line 24

**Comment by ksloan** [comment]
Changing line 24 to this fixes the issue. 
```var nodeEnabled = (undefined !== module && typeof require !== 'undefined');```

**Comment by kofrasa** [comment]
Fantastic work @ksloan. Could you please do the honours of submitting a PR?

**Comment by stevenvachon** [comment]
I'm getting this error with this line:
```js
const broquire = require("broquire")(require);
```
