### ISSUE TITLE
Partial use

### ISSUE THREAD

**Issue by stalniy** [kofrasa/mingo#52]
The minified file of the library is currently 30+ kB. Is there a way to use only operators and functions which I need? can I compile my own version of the library with help of tools like `rollup` or `webpack`?

It'd be good to provide ES6 version of the lib, so people will be able to use tree shaking and remove code which they don't use

**Comment by kofrasa** [comment]
Thanks for the ask @stalniy 

This work has been on my radar for a while since I initially built this library to target the browser. The options were:

1. Split library into multiple modules
2. Enable custom builds via a simple bundling tool

My preference is for option 2 however, I found the tools available generally try to do too many things which make things a bit complicated. 

I have also experimented with using ES6 in the past [mingo.js](https://github.com/kofrasa/mingo/blob/dev-es2015/mingo.js) but the generated code came out even larger. Perhaps this has gotten better.

I am happy to revisit this and will investigate the current tools available which can enable this in the simplest way possible. 

Thanks

**Comment by stalniy** [comment]
the easiest option is to use `rollup` + `babel` + `babel external helpers plugin`

**Comment by kofrasa** [comment]
Current port residing here. https://github.com/kofrasa/mingo/tree/dev-es6

A lot has change since I last looked at the ES6 landscape. I am very impressed with the latest tooling (`rollup` + `babel`). The generated code for `babel` has improved significantly.

Version 2.0.0 will support ES6 modules. Just a little bit of work left and this will merged into the main dev branch.

**Comment by stalniy** [comment]
Awesome! If you need help with rollup configuration to display correct coverage you can check my repository https://github.com/stalniy/casl/tree/master/tools

**Comment by kofrasa** [comment]
This should now be available on npm `v1.3.0`
