### ISSUE TITLE
ObjectId comparison

### ISSUE THREAD

**Issue by stalniy** [kofrasa/mingo#53]
this returns wrong result:
```js
const ObjectId = require('mongoose').Types.ObjectId
const { Query } = require('mingo')
const id = ObjectId()

const q = new Query({ id })

console.log(q.test({ id: id.toString() })) //false
console.log(q.test({ id: ObjectId(id.toString()) })) //false
```
I expect both checks to return true. 

Is there anyway to check equality of `ObjectId`s?

**Comment by kofrasa** [comment]
Thanks for report @stalniy 

Unfortunately, `mingo` only tests for identity when custom objects are supplied. It has no knowledge of the native MongoDB `ObjectId` type.

That said, it makes sense to run custom equality checks for values of the same type on a best effort basis such as: comparing their `toJSON()` or `toString()` methods if present. I will consider this in the next version.

You can temporarily check against the string value of `ObjectId` as a workaround. 

On a side note, I wrote `Mingo` first to target the client environment. Depending on the collection size, it will be more performant using the MongoDB query library directly if you are on the server.

**Comment by stalniy** [comment]
@kofrasa ObjectID comparison was not completely fixed. There are several cases which doesn't work:
```js
// oid - ObjectId constructor, id - instance of ObjectId

> new Query({ id }).test({ id: id })
true
> new Query({ id }).test({ id: oid(id.toString()) })
true

// the next cases fails
> new Query({ id }).test({ id: id.toString() })
false
> new Query({ id }).test({ id: id.toString() })
false
> new Query({ id: id.toString() }).test({ id })
```

**Comment by kofrasa** [comment]
Hi @stalniy 

User-defined types can only be compared on a best effort basis with the requirement that operands are of the **same type** (see my earlier comment), so this expected behaviour. 

That means comparing `ObjectId` against `String` will not work. However, two identical `ObjectId` values will compare correctly (as your second tests show). Previously, the only check for identity was using the `===` operator but the current release has improved on it by using hashes.

The library is not aware of custom types including ones defined by MongoDB. It is trivial for users to pass an identical type, or use a primitive javascript type for the operands. I think the behaviour is sound as is.

I am open to discuss if you have a different viewpoint.

Thanks

**Comment by stalniy** [comment]
Probably the best option is to allow to specify custom comparator for client types. For `ObjectId` it may look like:
```js
function compareObjectId(idA, idB) {
  const [valueA, valueB] = [String(idA), String(idB)]

  if (valueA === valueB) {
    return 0
  }

  return valueA > valueB ? 1 : -1
}
```

Then 
```js

mingo.setup({
   comparators: {
      ObjectId: compareObjectId
   }
})
```

what do you think?

**Comment by kofrasa** [comment]
This pattern can be confusing. I presume the use will be such: For unequal types, check whether the type name of any of the operands has a comparator. Use that to compare the types. 

The problem lies in checking either operand (what order?). If the operands aren't restricted to be of the same type, then one can also mistakenly register different types which compare against each other circularly.

Example: 
```{
comparators: {
  A: aCompareB,
  B: bCompareC,
  C: cCompareA
}
```

Obviously this is not sound, but `mingo` cannot tell. I did consider adding a comparator for the purposes of sorting custom types but opted out for simplicity. Even so, the restriction that both operands are of the same type would still hold to retain the principle of least surprise.

So even with comparators subject to the restrictions mentioned, your examples will still not pass.
It does seem to me that it is still simpler to use JS native types to avoid surprising semantics.

**Comment by voxsoftware** [comment]
I have same problem. I need a sort on ObjectId  objects. Why not use valueOf function? Or convert object to string? Or allow specify to library a object to primitive function converter for compare.

**Comment by jmbldwn** [comment]
I'm also looking for a solution.  

My database model (created using mongoose) has a field of type ObjectId.  I need to test for a match against a string version of the ObjectId.

I can certainly transform the string when creating the mingo query, but nothing I've done so far seems to work.  What's the trick to creating a query that will match on this type of field?

**Comment by jmbldwn** [comment]
The objects I am comparing to are coming from a MongoDB change stream, and I was hoping to just use them as-is without modification for my test.  I can alter my query if needed, but ideally it would the same query I normally use to do `find` operations.

My current workaround is to force the entire document to plain javascript types using `JSON.parse(JSON.stringify(doc))` but that feels kind of heavyweight.

**Comment by jmbldwn** [comment]
I did try that but no luck.  Maybe some kind of plugin mechanism?  I'm using this on the backend to route change stream events to the front-ends that need them, so there's plenty of room to pull in additional modules.

**Comment by jmbldwn** [comment]
That's what I tried to do.  It seems the ObjectId I created is different than what comes out of the change stream, so it wouldn't match.

**Comment by jmbldwn** [comment]
Right, I tried using the ObjectId class from the mongodb driver as well as the mongoose library, neither worked.

It may be that doing `JSON.parse(JSON.stringify())` is the best bet for what i'm doing.  Ultimately, I have to serialize these objects to send to front end clients so ObjectId classes are just an annoyance.

**Comment by stalniy** [comment]
Instead of providing a comparator settings, you could provide a setting to get primitive representation of an object. Like configurable `valueOf`, so then  people can define how their complex objects can be represented as primitives without additional mapping

**Comment by stalniy** [comment]
or you can do it even simpler, just allow to register custom `compare` function and let people on user land compare values in way they want.

This is how I solved this in my custom library (eventually I wrote a custom library to checking mongodb queries). You can take a look here -> https://github.com/stalniy/ucast/blob/master/packages/mongo2js/src/factory.ts#L26-L38
