### ISSUE TITLE
Mingo.setup() removed

### ISSUE THREAD

**Issue by serby** [kofrasa/mingo#56]
I use `setup` to change the default key from `_id`. Since the ES6 refactor this is no longer possible. 

`assert(typeof require('mingo').setup === 'function') Fails`

The readme shows setup `setup()` If it was intended to be remove this should be updated.

**Comment by kofrasa** [comment]
Thanks for reporting this bug @serby. 

The setup function was not exported after the major refactoring to ES6. See [index.js](https://github.com/kofrasa/mingo/blob/1a6fa8e3f7cddde93c3b7779edcb70b37b96c25d/lib/index.js)

**Comment by balaclark** [comment]
Thanks for this

**Comment by enochN** [comment]
Nice

**Comment by kofrasa** [comment]
Fixed in `v1.3.2`.

In the next major version, I may consider setting the default key to `id` rather than `_id`.  I think that is typical of objects in an in-memory collection, and also because `mingo` was initially written to be used in a fronted application where the `id` convention is most common.
