### ISSUE TITLE
Why is lodash a dependency?

### ISSUE THREAD

**Issue by Sleavely** [kofrasa/mingo#88]
I looked at package.json and it looks like lodash is being required, but not used anywhere within the repository. How come?

**Comment by kofrasa** [comment]
`Mingo` has zero production dependencies. `Lodash` is currently listed as a "devDependency" which I probably used in an old revision for testing. I have since switched to implementations from `Mingo` internals. I should make sometime to cleanup the unused "dev" dependencies.

If you are using `Mingo` in production, it does not require Lodash.
